FROM centos:7

RUN yum update -y
RUN yum group install -y "Development Tools" --exclude=java*,jna*
RUN yum install -y               \
        wget                     \
        mlocate                  \
        openssl-devel            \
        qt5-qtbase-devel         \
        qt5-qtscript

# install jdk-17
RUN wget https://download.java.net/java/GA/jdk17.0.2/dfd4a8d0985749f896bed50d7138ee7f/8/GPL/openjdk-17.0.2_linux-x64_bin.tar.gz
RUN tar xvf openjdk-17.0.2_linux-x64_bin.tar.gz
RUN mv jdk-17.0.2/ /opt/jdk-17/
RUN rm openjdk-17.0.2_linux-x64_bin.tar.gz
#RUN echo -e 'export JAVA_HOME=/opt/jdk-17\nexport PATH=$PATH:$JAVA_HOME/bin' >> /etc/profile
#RUN sed -i '$ a export JAVA_HOME=/opt/jdk-17\nexport PATH=$PATH:$JAVA_HOME/bin' /etc/profile
#RUN source /etc/profile
ENV JAVA_HOME=/opt/jdk-17
ENV PATH="${JAVA_HOME}/bin:${PATH}"

# change timezone
RUN rm /etc/localtime
RUN ln -s /usr/share/zoneinfo/Asia/Ulaanbaatar /etc/localtime

CMD /bin/bash && tail -f /dev/null
