FROM centos:8

RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
RUN yum update -y

RUN yum group install -y "Development Tools"
RUN yum install -y               \
        mlocate                  \
        openssl-devel            \
        qt5-qtbase-devel         \
        qt5-qtscript
RUN yum remove -y java*
RUN yum install -y java-17-openjdk-devel

# change timezone
RUN rm /etc/localtime
RUN ln -s /usr/share/zoneinfo/Asia/Ulaanbaatar /etc/localtime

CMD /bin/bash && tail -f /dev/null
